/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/CT.glb components/models/CT.tsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CT.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane047.geometry} material={materials.BEIGE} />
      <mesh geometry={nodes.Plane047_1.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Plane047_2.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Plane047_3.geometry} material={materials.SAND} />
      <mesh geometry={nodes.Plane047_4.geometry} material={materials.SAND} />
      <mesh geometry={nodes.Plane047_5.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_6.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_7.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Plane047_8.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Plane047_9.geometry} material={materials.RED} />
      <mesh geometry={nodes.Plane047_10.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_11.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_12.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_13.geometry} material={materials['Material.042']} />
      <mesh geometry={nodes.Plane047_14.geometry} material={materials.Threshold} />
      <mesh geometry={nodes.Plane047_15.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_16.geometry} material={materials.wood} />
      <mesh geometry={nodes.Plane047_17.geometry} material={materials['Dirty Wood Planks']} />
      <mesh geometry={nodes.Plane047_18.geometry} material={materials.WHITE} />
    </group>
  )
}

useGLTF.preload('/CT.glb')
