/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/CT_AUX.glb components/models/CT_AUX.tsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CT_AUX.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CT_AUX_OBS_1.geometry} material={materials['Rope mat']} />
      <mesh geometry={nodes.CT_AUX_OBS_2.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.CT_AUX_OBS_3.geometry} material={materials.Material} />
      <mesh geometry={nodes.CT_AUX_OBS_4.geometry} material={materials['Material.042']} />
      <mesh geometry={nodes.CT_AUX_OBS_5.geometry} material={materials['Material.017']} />
      <mesh geometry={nodes.CT_AUX_OBS_6.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.CT_AUX_OBS_7.geometry} material={nodes.CT_AUX_OBS_7.material} />
      <mesh geometry={nodes.CT_AUX_OBS_8.geometry} material={materials.Threshold} />
      <mesh geometry={nodes.CT_AUX_OBS_9.geometry} material={materials['Dirty Wood Planks']} />
      <mesh geometry={nodes.CT_AUX_OBS_10.geometry} material={materials.wood} />
      <mesh geometry={nodes.CT_AUX_OBS_11.geometry} material={materials['Old wood parquet']} />
      <mesh geometry={nodes.CT_AUX_OBS_12.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/CT_AUX.glb')
