/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/FINAL_GROUND.glb -t -r /public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    FINAL_GRID_1: THREE.Mesh
    FINAL_GRID_2: THREE.Mesh
    FINAL_GRID_3: THREE.Mesh
    FINAL_GRID_4: THREE.Mesh
    FINAL_GRID_5: THREE.Mesh
    FINAL_GRID_6: THREE.Mesh
    FINAL_GRID_7: THREE.Mesh
    FINAL_GRID_8: THREE.Mesh
    FINAL_GRID_9: THREE.Mesh
    FINAL_GRID_10: THREE.Mesh
    FINAL_GRID_11: THREE.Mesh
    FINAL_GRID_12: THREE.Mesh
    FINAL_GRID_13: THREE.Mesh
    FINAL_GRID_14: THREE.Mesh
    FINAL_GRID_15: THREE.Mesh
    FINAL_GRID_16: THREE.Mesh
    FINAL_GRID_17: THREE.Mesh
    FINAL_GRID_18: THREE.Mesh
    FINAL_GRID_19: THREE.Mesh
    FINAL_GRID_20: THREE.Mesh
    FINAL_GRID_21: THREE.Mesh
    FINAL_GRID_22: THREE.Mesh
    FINAL_GRID_23: THREE.Mesh
    FINAL_GRID_24: THREE.Mesh
    FINAL_GRID_25: THREE.Mesh
    FINAL_GRID_26: THREE.Mesh
    FINAL_GRID_27: THREE.Mesh
    FINAL_GRID_28: THREE.Mesh
    FINAL_GRID_29: THREE.Mesh
    FINAL_GRID_30: THREE.Mesh
    FINAL_GRID_31: THREE.Mesh
    FINAL_GRID_32: THREE.Mesh
    FINAL_GRID_33: THREE.Mesh
    FINAL_GRID_34: THREE.Mesh
    FINAL_GRID_35: THREE.Mesh
    FINAL_GRID_36: THREE.Mesh
    FINAL_GRID_37: THREE.Mesh
    FINAL_GRID_38: THREE.Mesh
    FINAL_GRID_39: THREE.Mesh
    FINAL_GRID_40: THREE.Mesh
    FINAL_GRID_41: THREE.Mesh
    FINAL_GRID_42: THREE.Mesh
    FINAL_GRID_43: THREE.Mesh
    FINAL_GRID_44: THREE.Mesh
    FINAL_GRID_45: THREE.Mesh
    FINAL_GRID_46: THREE.Mesh
    FINAL_GRID_47: THREE.Mesh
    FINAL_GRID_48: THREE.Mesh
    FINAL_GRID_49: THREE.Mesh
    FINAL_GRID_50: THREE.Mesh
    FINAL_GRID_51: THREE.Mesh
    FINAL_GRID_52: THREE.Mesh
    FINAL_GRID_53: THREE.Mesh
    FINAL_GRID_54: THREE.Mesh
    FINAL_GRID_55: THREE.Mesh
    FINAL_GRID_56: THREE.Mesh
    FINAL_GRID_57: THREE.Mesh
    FINAL_GRID_58: THREE.Mesh
    FINAL_GRID_59: THREE.Mesh
    FINAL_GRID_60: THREE.Mesh
    FINAL_GRID_61: THREE.Mesh
    FINAL_GRID_62: THREE.Mesh
    FINAL_GRID_63: THREE.Mesh
    FINAL_GRID_64: THREE.Mesh
    FINAL_GRID_65: THREE.Mesh
    FINAL_GRID_66: THREE.Mesh
    FINAL_GRID_67: THREE.Mesh
    FINAL_GRID_68: THREE.Mesh
    FINAL_GRID_69: THREE.Mesh
    FINAL_GRID_70: THREE.Mesh
    FINAL_GRID_71: THREE.Mesh
    FINAL_GRID_72: THREE.Mesh
    FINAL_GRID_73: THREE.Mesh
    FINAL_GRID_74: THREE.Mesh
    FINAL_GRID_75: THREE.Mesh
    FINAL_GRID_76: THREE.Mesh
    FINAL_GRID_77: THREE.Mesh
    FINAL_GRID_78: THREE.Mesh
    FINAL_GRID_79: THREE.Mesh
    FINAL_GRID_80: THREE.Mesh
    FINAL_GRID_81: THREE.Mesh
    FINAL_GRID_82: THREE.Mesh
    FINAL_GRID_83: THREE.Mesh
    FINAL_GRID_84: THREE.Mesh
    FINAL_GRID_85: THREE.Mesh
    FINAL_GRID_86: THREE.Mesh
    FINAL_GRID_87: THREE.Mesh
    FINAL_GRID_88: THREE.Mesh
    FINAL_GRID_89: THREE.Mesh
    FINAL_GRID_90: THREE.Mesh
    FINAL_GRID_91: THREE.Mesh
    FINAL_GRID_92: THREE.Mesh
    FINAL_GRID_93: THREE.Mesh
    FINAL_GRID_94: THREE.Mesh
    FINAL_GRID_95: THREE.Mesh
    FINAL_GRID_96: THREE.Mesh
    FINAL_GRID_97: THREE.Mesh
    FINAL_GRID_98: THREE.Mesh
    FINAL_GRID_99: THREE.Mesh
    FINAL_GRID_100: THREE.Mesh
    FINAL_GRID_101: THREE.Mesh
    FINAL_GRID_102: THREE.Mesh
    FINAL_GRID_103: THREE.Mesh
    FINAL_GRID_104: THREE.Mesh
    FINAL_GRID_105: THREE.Mesh
    FINAL_GRID_106: THREE.Mesh
    FINAL_GRID_107: THREE.Mesh
    FINAL_GRID_108: THREE.Mesh
    FINAL_GRID_109: THREE.Mesh
    FINAL_GRID_110: THREE.Mesh
    FINAL_GRID_111: THREE.Mesh
    FINAL_GRID_112: THREE.Mesh
    FINAL_GRID_113: THREE.Mesh
    FINAL_GRID_114: THREE.Mesh
    FINAL_GRID_115: THREE.Mesh
    FINAL_GRID_116: THREE.Mesh
    FINAL_GRID_117: THREE.Mesh
    FINAL_GRID_118: THREE.Mesh
    FINAL_GRID_119: THREE.Mesh
    FINAL_GRID_120: THREE.Mesh
    FINAL_GRID_121: THREE.Mesh
    FINAL_GRID_122: THREE.Mesh
    FINAL_GRID_123: THREE.Mesh
    FINAL_GRID_124: THREE.Mesh
    FINAL_GRID_125: THREE.Mesh
    FINAL_GRID_126: THREE.Mesh
    FINAL_GRID_127: THREE.Mesh
    FINAL_GRID_128: THREE.Mesh
    FINAL_GRID_129: THREE.Mesh
    FINAL_GRID_130: THREE.Mesh
    FINAL_GRID_131: THREE.Mesh
    FINAL_GRID_132: THREE.Mesh
    FINAL_GRID_133: THREE.Mesh
    FINAL_GRID_134: THREE.Mesh
    FINAL_GRID_135: THREE.Mesh
    FINAL_GRID_136: THREE.Mesh
    FINAL_GRID_137: THREE.Mesh
    FINAL_GRID_138: THREE.Mesh
    FINAL_GRID_139: THREE.Mesh
    FINAL_GRID_140: THREE.Mesh
    FINAL_GRID_141: THREE.Mesh
    FINAL_GRID_142: THREE.Mesh
    FINAL_GRID_143: THREE.Mesh
    FINAL_GRID_144: THREE.Mesh
    FINAL_GRID_145: THREE.Mesh
    FINAL_GRID_146: THREE.Mesh
    FINAL_GRID_147: THREE.Mesh
    FINAL_GRID_148: THREE.Mesh
    FINAL_GRID_149: THREE.Mesh
    FINAL_GRID_150: THREE.Mesh
    FINAL_GRID_151: THREE.Mesh
    FINAL_GRID_152: THREE.Mesh
    FINAL_GRID_153: THREE.Mesh
    FINAL_GRID_154: THREE.Mesh
    FINAL_GRID_155: THREE.Mesh
    FINAL_GRID_156: THREE.Mesh
    FINAL_GRID_157: THREE.Mesh
    FINAL_GRID_158: THREE.Mesh
    FINAL_GRID_159: THREE.Mesh
    FINAL_GRID_160: THREE.Mesh
    FINAL_GRID_161: THREE.Mesh
    FINAL_GRID_162: THREE.Mesh
    FINAL_GRID_163: THREE.Mesh
    FINAL_GRID_164: THREE.Mesh
    FINAL_GRID_165: THREE.Mesh
    FINAL_GRID_166: THREE.Mesh
    FINAL_GRID_167: THREE.Mesh
    FINAL_GRID_168: THREE.Mesh
    FINAL_GRID_169: THREE.Mesh
    FINAL_GRID_170: THREE.Mesh
    FINAL_GRID_171: THREE.Mesh
    FINAL_GRID_172: THREE.Mesh
    FINAL_GRID_173: THREE.Mesh
    FINAL_GRID_174: THREE.Mesh
    FINAL_GRID_175: THREE.Mesh
    FINAL_GRID_176: THREE.Mesh
    FINAL_GRID_177: THREE.Mesh
    FINAL_GRID_178: THREE.Mesh
    FINAL_GRID_179: THREE.Mesh
    FINAL_GRID_180: THREE.Mesh
    FINAL_GRID_181: THREE.Mesh
    FINAL_GRID_182: THREE.Mesh
    FINAL_GRID_183: THREE.Mesh
    FINAL_GRID_184: THREE.Mesh
    FINAL_GRID_185: THREE.Mesh
    FINAL_GRID_186: THREE.Mesh
    FINAL_GRID_187: THREE.Mesh
    FINAL_GRID_188: THREE.Mesh
    FINAL_GRID_189: THREE.Mesh
  }
  materials: {
    BEACH: THREE.MeshStandardMaterial
    Palm_Bark: THREE.MeshStandardMaterial
    palm_leaf2: THREE.MeshStandardMaterial
    Dry_palm: THREE.MeshPhysicalMaterial
    Coconut: THREE.MeshStandardMaterial
    Palm_Leaves: THREE.MeshPhysicalMaterial
    palm_bark_top: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    FINISH_LINE: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    NAMEPLATE: THREE.MeshStandardMaterial
    START_LINE: THREE.MeshStandardMaterial
    ['Material.075']: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    ['BLUE.001']: THREE.MeshStandardMaterial
    ['Material.045']: THREE.MeshStandardMaterial
    ['Material.046']: THREE.MeshStandardMaterial
    RUBBER: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['House Gate.001']: THREE.MeshStandardMaterial
    GREY: THREE.MeshStandardMaterial
    ['Material.144']: THREE.MeshStandardMaterial
    ['Material.143']: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    ['Material.077']: THREE.MeshStandardMaterial
    ['wood.001']: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    ['white.001']: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    GREY: THREE.MeshStandardMaterial
    ['wood.002']: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['House Gate']: THREE.MeshStandardMaterial
    GREY: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    ROPE: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    GREY: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    ROPE: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    GREY: THREE.MeshStandardMaterial
    ['wood.001']: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ['white.001']: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    GREY: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    ['Material.158']: THREE.MeshStandardMaterial
    ['Material.157']: THREE.MeshStandardMaterial
    ['Material.165']: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    ['House Gate']: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    ['white.001']: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    ['House Gate.002']: THREE.MeshStandardMaterial
    ['wood.001']: THREE.MeshStandardMaterial
    ['white.002']: THREE.MeshStandardMaterial
    ['Material.171']: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    ['House Gate.001']: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    ['Material.176']: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    GREEN: THREE.MeshStandardMaterial
    ALLEYS: THREE.MeshStandardMaterial
    GRASS: THREE.MeshStandardMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    FINISH_LINE: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    START_LINE: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    BLACK: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    GREEN: THREE.MeshStandardMaterial
    FINISH_LINE: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    START_LINE: THREE.MeshStandardMaterial
    ORANGE_TEXT: THREE.MeshStandardMaterial
    NAMEPLATE: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    RUBBER: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['START_LINE.SMALL']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
    HOLE: THREE.MeshStandardMaterial
    ['Material.052']: THREE.MeshStandardMaterial
    ['Material.055']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    BEIGE: THREE.MeshStandardMaterial
    ['Dirty Wood Planks']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['ORANGE_TEXT.001']: THREE.MeshStandardMaterial
    ['GREEN.001']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    FINISH_LINE: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    START_LINE: THREE.MeshStandardMaterial
    ['Dry Sand']: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ['White Painted Wood']: THREE.MeshPhysicalMaterial
    ['WHITE METAL']: THREE.MeshStandardMaterial
    ['RED METAL']: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    ['Dry Sand']: THREE.MeshStandardMaterial
    ['WHITE METAL']: THREE.MeshStandardMaterial
    ['RED METAL']: THREE.MeshStandardMaterial
    ['Metal Rust Rope']: THREE.MeshStandardMaterial
    ['WHITE METAL']: THREE.MeshStandardMaterial
    CONCRETE: THREE.MeshStandardMaterial
    ['Dry Sand']: THREE.MeshStandardMaterial
    CONCRETE: THREE.MeshStandardMaterial
    ROPE: THREE.MeshStandardMaterial
    ['White Painted Wood']: THREE.MeshPhysicalMaterial
    ['Aged White Metal']: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    ['Dry Sand']: THREE.MeshStandardMaterial
    CONCRETE: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
    GTOPIC: THREE.MeshStandardMaterial
    SIGNAGE: THREE.MeshStandardMaterial
    LOGO: THREE.MeshStandardMaterial
    METAL: THREE.MeshStandardMaterial
    GOLD: THREE.MeshPhysicalMaterial
    WHITE_TEXT: THREE.MeshStandardMaterial
    Bricks: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    BROWN: THREE.MeshStandardMaterial
    FINISH_LINE: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    START_LINE: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    RUBBER: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    Green2: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/../I DRIVE/SSBWISV/public/FINAL_GROUND.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.599, 1.472, -6.877]} rotation={[0, -0.04, 0]}>
        <mesh geometry={nodes.FINAL_GRID_1.geometry} material={materials.BEACH} />
        <mesh geometry={nodes.FINAL_GRID_2.geometry} material={nodes.FINAL_GRID_2.material} />
        <mesh geometry={nodes.FINAL_GRID_3.geometry} material={materials.Palm_Bark} />
        <mesh geometry={nodes.FINAL_GRID_4.geometry} material={materials.palm_leaf2} />
        <mesh geometry={nodes.FINAL_GRID_5.geometry} material={materials.Dry_palm} />
        <mesh geometry={nodes.FINAL_GRID_6.geometry} material={materials.Coconut} />
        <mesh geometry={nodes.FINAL_GRID_7.geometry} material={materials.Palm_Leaves} />
        <mesh geometry={nodes.FINAL_GRID_8.geometry} material={materials.palm_bark_top} />
        <mesh geometry={nodes.FINAL_GRID_9.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.FINAL_GRID_10.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.FINAL_GRID_11.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.FINAL_GRID_12.geometry} material={materials.FINISH_LINE} />
        <mesh geometry={nodes.FINAL_GRID_13.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_14.geometry} material={materials.NAMEPLATE} />
        <mesh geometry={nodes.FINAL_GRID_15.geometry} material={materials.START_LINE} />
        <mesh geometry={nodes.FINAL_GRID_16.geometry} material={materials['Material.075']} />
        <mesh geometry={nodes.FINAL_GRID_17.geometry} material={materials.RED} />
        <mesh geometry={nodes.FINAL_GRID_18.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.FINAL_GRID_19.geometry} material={materials['BLUE.001']} />
        <mesh geometry={nodes.FINAL_GRID_20.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.FINAL_GRID_21.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.FINAL_GRID_22.geometry} material={materials.RUBBER} />
        <mesh geometry={nodes.FINAL_GRID_23.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.FINAL_GRID_24.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.FINAL_GRID_25.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.FINAL_GRID_26.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.FINAL_GRID_27.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.FINAL_GRID_28.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.FINAL_GRID_29.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.FINAL_GRID_30.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.FINAL_GRID_31.geometry} material={materials['House Gate.001']} />
        <mesh geometry={nodes.FINAL_GRID_32.geometry} material={materials.GREY} />
        <mesh geometry={nodes.FINAL_GRID_33.geometry} material={materials['Material.144']} />
        <mesh geometry={nodes.FINAL_GRID_34.geometry} material={materials['Material.143']} />
        <mesh geometry={nodes.FINAL_GRID_35.geometry} material={materials.white} />
        <mesh geometry={nodes.FINAL_GRID_36.geometry} material={materials['Material.077']} />
        <mesh geometry={nodes.FINAL_GRID_37.geometry} material={materials['wood.001']} />
        <mesh geometry={nodes.FINAL_GRID_38.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_39.geometry} material={materials['white.001']} />
        <mesh geometry={nodes.FINAL_GRID_40.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_41.geometry} material={materials.GREY} />
        <mesh geometry={nodes.FINAL_GRID_42.geometry} material={materials['wood.002']} />
        <mesh geometry={nodes.FINAL_GRID_43.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_44.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_45.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.FINAL_GRID_46.geometry} material={materials['House Gate']} />
        <mesh geometry={nodes.FINAL_GRID_47.geometry} material={materials.GREY} />
        <mesh geometry={nodes.FINAL_GRID_48.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_49.geometry} material={materials.ROPE} />
        <mesh geometry={nodes.FINAL_GRID_50.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_51.geometry} material={materials.GREY} />
        <mesh geometry={nodes.FINAL_GRID_52.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_53.geometry} material={materials.ROPE} />
        <mesh geometry={nodes.FINAL_GRID_54.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_55.geometry} material={materials.GREY} />
        <mesh geometry={nodes.FINAL_GRID_56.geometry} material={materials['wood.001']} />
        <mesh geometry={nodes.FINAL_GRID_57.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_58.geometry} material={materials.RED} />
        <mesh geometry={nodes.FINAL_GRID_59.geometry} material={materials['white.001']} />
        <mesh geometry={nodes.FINAL_GRID_60.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_61.geometry} material={materials.GREY} />
        <mesh geometry={nodes.FINAL_GRID_62.geometry} material={materials.wood} />
        <mesh geometry={nodes.FINAL_GRID_63.geometry} material={materials.white} />
        <mesh geometry={nodes.FINAL_GRID_64.geometry} material={materials['Material.158']} />
        <mesh geometry={nodes.FINAL_GRID_65.geometry} material={materials['Material.157']} />
        <mesh geometry={nodes.FINAL_GRID_66.geometry} material={materials['Material.165']} />
        <mesh geometry={nodes.FINAL_GRID_67.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_68.geometry} material={materials['House Gate']} />
        <mesh geometry={nodes.FINAL_GRID_69.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_70.geometry} material={materials['white.001']} />
        <mesh geometry={nodes.FINAL_GRID_71.geometry} material={materials.RED} />
        <mesh geometry={nodes.FINAL_GRID_72.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_73.geometry} material={materials['House Gate.002']} />
        <mesh geometry={nodes.FINAL_GRID_74.geometry} material={materials['wood.001']} />
        <mesh geometry={nodes.FINAL_GRID_75.geometry} material={materials['white.002']} />
        <mesh geometry={nodes.FINAL_GRID_76.geometry} material={materials['Material.171']} />
        <mesh geometry={nodes.FINAL_GRID_77.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_78.geometry} material={materials['House Gate.001']} />
        <mesh geometry={nodes.FINAL_GRID_79.geometry} material={materials.wood} />
        <mesh geometry={nodes.FINAL_GRID_80.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.FINAL_GRID_81.geometry} material={materials.white} />
        <mesh geometry={nodes.FINAL_GRID_82.geometry} material={materials['Material.176']} />
        <mesh geometry={nodes.FINAL_GRID_83.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_84.geometry} material={materials.GREEN} />
        <mesh geometry={nodes.FINAL_GRID_85.geometry} material={materials.ALLEYS} />
        <mesh geometry={nodes.FINAL_GRID_86.geometry} material={materials.GRASS} />
        <mesh geometry={nodes.FINAL_GRID_87.geometry} material={materials['Material.066']} />
        <mesh geometry={nodes.FINAL_GRID_88.geometry} material={materials.FINISH_LINE} />
        <mesh geometry={nodes.FINAL_GRID_89.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_90.geometry} material={materials.START_LINE} />
        <mesh geometry={nodes.FINAL_GRID_91.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.FINAL_GRID_92.geometry} material={materials.RED} />
        <mesh geometry={nodes.FINAL_GRID_93.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.FINAL_GRID_94.geometry} material={materials.BLACK} />
        <mesh geometry={nodes.FINAL_GRID_95.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.FINAL_GRID_96.geometry} material={materials.GREEN} />
        <mesh geometry={nodes.FINAL_GRID_97.geometry} material={materials.FINISH_LINE} />
        <mesh geometry={nodes.FINAL_GRID_98.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_99.geometry} material={materials.START_LINE} />
        <mesh geometry={nodes.FINAL_GRID_100.geometry} material={materials.ORANGE_TEXT} />
        <mesh geometry={nodes.FINAL_GRID_101.geometry} material={materials.NAMEPLATE} />
        <mesh geometry={nodes.FINAL_GRID_102.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.FINAL_GRID_103.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.FINAL_GRID_104.geometry} material={materials.RUBBER} />
        <mesh geometry={nodes.FINAL_GRID_105.geometry} material={materials.RED} />
        <mesh geometry={nodes.FINAL_GRID_106.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.FINAL_GRID_107.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.FINAL_GRID_108.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.FINAL_GRID_109.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.FINAL_GRID_110.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.FINAL_GRID_111.geometry} material={materials['START_LINE.SMALL']} />
        <mesh geometry={nodes.FINAL_GRID_112.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.FINAL_GRID_113.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.FINAL_GRID_114.geometry} material={materials.HOLE} />
        <mesh geometry={nodes.FINAL_GRID_115.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.FINAL_GRID_116.geometry} material={materials['Material.055']} />
        <mesh geometry={nodes.FINAL_GRID_117.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.FINAL_GRID_118.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.FINAL_GRID_119.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.FINAL_GRID_120.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.FINAL_GRID_121.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.FINAL_GRID_122.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.FINAL_GRID_123.geometry} material={materials.BEIGE} />
        <mesh geometry={nodes.FINAL_GRID_124.geometry} material={materials['Dirty Wood Planks']} />
        <mesh geometry={nodes.FINAL_GRID_125.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.FINAL_GRID_126.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.FINAL_GRID_127.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.FINAL_GRID_128.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.FINAL_GRID_129.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.FINAL_GRID_130.geometry} material={materials['ORANGE_TEXT.001']} />
        <mesh geometry={nodes.FINAL_GRID_131.geometry} material={materials['GREEN.001']} />
        <mesh geometry={nodes.FINAL_GRID_132.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.FINAL_GRID_133.geometry} material={materials.FINISH_LINE} />
        <mesh geometry={nodes.FINAL_GRID_134.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_135.geometry} material={materials.START_LINE} />
        <mesh geometry={nodes.FINAL_GRID_136.geometry} material={materials['Dry Sand']} />
        <mesh geometry={nodes.FINAL_GRID_137.geometry} material={materials.RED} />
        <mesh geometry={nodes.FINAL_GRID_138.geometry} material={materials['White Painted Wood']} />
        <mesh geometry={nodes.FINAL_GRID_139.geometry} material={materials['WHITE METAL']} />
        <mesh geometry={nodes.FINAL_GRID_140.geometry} material={materials['RED METAL']} />
        <mesh geometry={nodes.FINAL_GRID_141.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_142.geometry} material={materials.SAND} />
        <mesh geometry={nodes.FINAL_GRID_143.geometry} material={materials.RED} />
        <mesh geometry={nodes.FINAL_GRID_144.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_145.geometry} material={materials['Dry Sand']} />
        <mesh geometry={nodes.FINAL_GRID_146.geometry} material={materials['WHITE METAL']} />
        <mesh geometry={nodes.FINAL_GRID_147.geometry} material={materials['RED METAL']} />
        <mesh geometry={nodes.FINAL_GRID_148.geometry} material={materials['Metal Rust Rope']} />
        <mesh geometry={nodes.FINAL_GRID_149.geometry} material={materials['WHITE METAL']} />
        <mesh geometry={nodes.FINAL_GRID_150.geometry} material={materials.CONCRETE} />
        <mesh geometry={nodes.FINAL_GRID_151.geometry} material={materials['Dry Sand']} />
        <mesh geometry={nodes.FINAL_GRID_152.geometry} material={materials.CONCRETE} />
        <mesh geometry={nodes.FINAL_GRID_153.geometry} material={materials.ROPE} />
        <mesh geometry={nodes.FINAL_GRID_154.geometry} material={materials['White Painted Wood']} />
        <mesh geometry={nodes.FINAL_GRID_155.geometry} material={materials['Aged White Metal']} />
        <mesh geometry={nodes.FINAL_GRID_156.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_157.geometry} material={materials['Dry Sand']} />
        <mesh geometry={nodes.FINAL_GRID_158.geometry} material={materials.CONCRETE} />
        <mesh geometry={nodes.FINAL_GRID_159.geometry} material={materials.Grass} />
        <mesh geometry={nodes.FINAL_GRID_160.geometry} material={materials.GTOPIC} />
        <mesh geometry={nodes.FINAL_GRID_161.geometry} material={materials.SIGNAGE} />
        <mesh geometry={nodes.FINAL_GRID_162.geometry} material={materials.LOGO} />
        <mesh geometry={nodes.FINAL_GRID_163.geometry} material={materials.METAL} />
        <mesh geometry={nodes.FINAL_GRID_164.geometry} material={materials.GOLD} />
        <mesh geometry={nodes.FINAL_GRID_165.geometry} material={materials.WHITE_TEXT} />
        <mesh geometry={nodes.FINAL_GRID_166.geometry} material={materials.Bricks} />
        <mesh geometry={nodes.FINAL_GRID_167.geometry} material={materials.Green} />
        <mesh geometry={nodes.FINAL_GRID_168.geometry} material={materials.BROWN} />
        <mesh geometry={nodes.FINAL_GRID_169.geometry} material={materials.FINISH_LINE} />
        <mesh geometry={nodes.FINAL_GRID_170.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FINAL_GRID_171.geometry} material={materials.START_LINE} />
        <mesh geometry={nodes.FINAL_GRID_172.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.FINAL_GRID_173.geometry} material={materials.RUBBER} />
        <mesh geometry={nodes.FINAL_GRID_174.geometry} material={materials.RED} />
        <mesh geometry={nodes.FINAL_GRID_175.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.FINAL_GRID_176.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.FINAL_GRID_177.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.FINAL_GRID_178.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.FINAL_GRID_179.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.FINAL_GRID_180.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.FINAL_GRID_181.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.FINAL_GRID_182.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.FINAL_GRID_183.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.FINAL_GRID_184.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.FINAL_GRID_185.geometry} material={materials.Green2} />
        <mesh geometry={nodes.FINAL_GRID_186.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.FINAL_GRID_187.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.FINAL_GRID_188.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.FINAL_GRID_189.geometry} material={materials['Material.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/../I DRIVE/SSBWISV/public/FINAL_GROUND.glb')
