/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Gate.glb components/models/Gate.tsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Gate.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder839.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Cylinder839_1.geometry} material={materials['The GTO']} />
      <mesh geometry={nodes.Cylinder839_2.geometry} material={materials['Material.048']} />
      <mesh geometry={nodes.Cylinder839_3.geometry} material={materials['Material.037']} />
      <mesh geometry={nodes.Cylinder839_4.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cylinder839_5.geometry} material={materials['Bricks.001']} />
      <mesh geometry={nodes.Cylinder839_6.geometry} material={materials['Material.028']} />
      <mesh geometry={nodes.Cylinder839_7.geometry} material={materials['Material.066']} />
      <mesh geometry={nodes.Cylinder839_8.geometry} material={materials['Material.044']} />
    </group>
  )
}

useGLTF.preload('/Gate.glb')
