/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Ground.glb components/models/Ground.tsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Ground.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} />
      <mesh geometry={nodes.Plane014_1.geometry} material={materials['Material.119']} />
      <mesh geometry={nodes.Plane014_2.geometry} material={materials['Soil Ground']} />
    </group>
  )
}

useGLTF.preload('/Ground.glb')
