/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/HGT.glb components/models/HGT.tsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/HGT.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text407.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Text407_1.geometry} material={materials['Material.017']} />
      <mesh geometry={nodes.Text407_2.geometry} material={materials['Material.042']} />
      <mesh geometry={nodes.Text407_3.geometry} material={materials.Material} />
      <mesh geometry={nodes.Text407_4.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Text407_5.geometry} material={nodes.Text407_5.material} />
      <mesh geometry={nodes.Text407_6.geometry} material={materials['Material.066']} />
      <mesh geometry={nodes.Text407_7.geometry} material={materials.RED} />
      <mesh geometry={nodes.Text407_8.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Text407_9.geometry} material={materials['Material.049']} />
    </group>
  )
}

useGLTF.preload('/HGT.glb')
