/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/IND_OBS.glb components/models/IND_OBS.tsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/IND_OBS.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.IND_OBS_1.geometry} material={materials.SAND} />
      <mesh geometry={nodes.IND_OBS_2.geometry} material={materials['House Gate']} />
      <mesh geometry={nodes.IND_OBS_3.geometry} material={materials.wood} />
      <mesh geometry={nodes.IND_OBS_4.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.IND_OBS_5.geometry} material={materials['Material.135']} />
      <mesh geometry={nodes.IND_OBS_6.geometry} material={materials['Material.144']} />
      <mesh geometry={nodes.IND_OBS_7.geometry} material={materials['Material.143']} />
      <mesh geometry={nodes.IND_OBS_8.geometry} material={nodes.IND_OBS_8.material} />
      <mesh geometry={nodes.IND_OBS_9.geometry} material={materials['Material.142']} />
      <mesh geometry={nodes.IND_OBS_10.geometry} material={materials['Material.141']} />
      <mesh geometry={nodes.IND_OBS_11.geometry} material={materials['Material.140']} />
      <mesh geometry={nodes.IND_OBS_12.geometry} material={materials['Material.139']} />
      <mesh geometry={nodes.IND_OBS_13.geometry} material={materials['Material.138']} />
      <mesh geometry={nodes.IND_OBS_14.geometry} material={materials['Material.137']} />
      <mesh geometry={nodes.IND_OBS_15.geometry} material={materials['Material.159']} />
      <mesh geometry={nodes.IND_OBS_16.geometry} material={materials['Material.158']} />
      <mesh geometry={nodes.IND_OBS_17.geometry} material={materials['Material.157']} />
      <mesh geometry={nodes.IND_OBS_18.geometry} material={materials['Material.156']} />
      <mesh geometry={nodes.IND_OBS_19.geometry} material={materials['Material.155']} />
      <mesh geometry={nodes.IND_OBS_20.geometry} material={materials['Material.151']} />
      <mesh geometry={nodes.IND_OBS_21.geometry} material={materials['Material.145']} />
      <mesh geometry={nodes.IND_OBS_22.geometry} material={materials['Material.150']} />
      <mesh geometry={nodes.IND_OBS_23.geometry} material={materials['Material.146']} />
      <mesh geometry={nodes.IND_OBS_24.geometry} material={materials['Material.147']} />
      <mesh geometry={nodes.IND_OBS_25.geometry} material={materials['Material.148']} />
      <mesh geometry={nodes.IND_OBS_26.geometry} material={materials['Material.149']} />
      <mesh geometry={nodes.IND_OBS_27.geometry} material={materials['Material.176']} />
      <mesh geometry={nodes.IND_OBS_28.geometry} material={materials['Material.170']} />
      <mesh geometry={nodes.IND_OBS_29.geometry} material={materials['Material.169']} />
      <mesh geometry={nodes.IND_OBS_30.geometry} material={materials['Material.171']} />
      <mesh geometry={nodes.IND_OBS_31.geometry} material={materials['Material.167']} />
      <mesh geometry={nodes.IND_OBS_32.geometry} material={materials['Material.166']} />
      <mesh geometry={nodes.IND_OBS_33.geometry} material={materials['Material.165']} />
      <mesh geometry={nodes.IND_OBS_34.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.IND_OBS_35.geometry} material={materials['Material.050']} />
      <mesh geometry={nodes.IND_OBS_36.geometry} material={materials['Material.049']} />
      <mesh geometry={nodes.IND_OBS_37.geometry} material={materials['Forge iron']} />
      <mesh geometry={nodes.IND_OBS_38.geometry} material={materials.Beams} />
      <mesh geometry={nodes.IND_OBS_39.geometry} material={materials.barbed_wire} />
    </group>
  )
}

useGLTF.preload('/IND_OBS.glb')
