/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Pathway.glb components/models/Pathway.tsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pathway.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PathWAY001.geometry} material={materials.BROWN} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/Pathway.glb')
