/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/PGT_BASE.glb components/models/PGT_BASE.tsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/PGT_BASE.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube1286.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Cube1286_1.geometry} material={nodes.Cube1286_1.material} />
        <mesh geometry={nodes.Cube1286_2.geometry} material={materials['Material.070']} />
        <mesh geometry={nodes.Cube1286_3.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Cube1286_4.geometry} material={materials.RED} />
        <mesh geometry={nodes.Cube1286_5.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube1286_6.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube1286_7.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.Cube1286_8.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Cube1286_9.geometry} material={materials['Material.131']} />
        <mesh geometry={nodes.Cube1286_10.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Cube1286_11.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Cube1286_12.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube1286_13.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Cube1286_14.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube1286_15.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube1286_16.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube1286_17.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube1286_18.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Cube1286_19.geometry} material={materials['Material.049']} />
        <mesh geometry={nodes.Cube1286_20.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Cube1286_21.geometry} material={materials['Material.066']} />
        <mesh geometry={nodes.Cube1286_22.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube1286_23.geometry} material={materials['Material.170']} />
        <mesh geometry={nodes.Cube1286_24.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube1286_25.geometry} material={materials['Material.023']} />
      </group>
    </group>
  )
}

useGLTF.preload('/PGT_BASE.glb')
