/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/CT.glb --output components/models/CT.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane047: THREE.Mesh
    Plane047_1: THREE.Mesh
    Plane047_2: THREE.Mesh
    Plane047_3: THREE.Mesh
    Plane047_4: THREE.Mesh
    Plane047_5: THREE.Mesh
    Plane047_6: THREE.Mesh
    Plane047_7: THREE.Mesh
    Plane047_8: THREE.Mesh
    Plane047_9: THREE.Mesh
    Plane047_10: THREE.Mesh
    Plane047_11: THREE.Mesh
    Plane047_12: THREE.Mesh
    Plane047_13: THREE.Mesh
    Plane047_14: THREE.Mesh
    Plane047_15: THREE.Mesh
    Plane047_16: THREE.Mesh
    Plane047_17: THREE.Mesh
    Plane047_18: THREE.Mesh
  }
  materials: {
    BEIGE: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    Threshold: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    ['Dirty Wood Planks']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/CT.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane047.geometry} material={materials.BEIGE} />
      <mesh geometry={nodes.Plane047_1.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Plane047_2.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Plane047_3.geometry} material={materials.SAND} />
      <mesh geometry={nodes.Plane047_4.geometry} material={materials.SAND} />
      <mesh geometry={nodes.Plane047_5.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_6.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_7.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Plane047_8.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Plane047_9.geometry} material={materials.RED} />
      <mesh geometry={nodes.Plane047_10.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_11.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_12.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_13.geometry} material={materials['Material.042']} />
      <mesh geometry={nodes.Plane047_14.geometry} material={materials.Threshold} />
      <mesh geometry={nodes.Plane047_15.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_16.geometry} material={materials.wood} />
      <mesh geometry={nodes.Plane047_17.geometry} material={materials['Dirty Wood Planks']} />
      <mesh geometry={nodes.Plane047_18.geometry} material={materials.WHITE} />
    </group>
  )
}

useGLTF.preload('/CT.glb')
