/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/CT.glb -o components/models/CT.tsx 
*/
/* eslint-disable react/no-unknown-property */

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder567: THREE.Mesh
    Plane047: THREE.Mesh
    Plane047_1: THREE.Mesh
    Plane047_2: THREE.Mesh
    Plane047_3: THREE.Mesh
    Plane047_4: THREE.Mesh
    Plane047_5: THREE.Mesh
    CT_BORDER: THREE.Mesh
    Plane017: THREE.Mesh
    Plane017_1: THREE.Mesh
    Plane017_2: THREE.Mesh
    Plane017_3: THREE.Mesh
    Plane024: THREE.Mesh
    Plane024_1: THREE.Mesh
    Plane024_2: THREE.Mesh
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
    Plane010_2: THREE.Mesh
    Plane011: THREE.Mesh
    Plane011_1: THREE.Mesh
    Plane011_2: THREE.Mesh
    Plane013: THREE.Mesh
    Plane013_1: THREE.Mesh
    Plane013_2: THREE.Mesh
    Plane015: THREE.Mesh
    Plane015_1: THREE.Mesh
    Plane015_2: THREE.Mesh
    Plane016: THREE.Mesh
    Plane016_1: THREE.Mesh
    Plane016_2: THREE.Mesh
    Plane018: THREE.Mesh
    Plane018_1: THREE.Mesh
    Plane018_2: THREE.Mesh
    Plane019: THREE.Mesh
    Plane019_1: THREE.Mesh
    Plane020: THREE.Mesh
    Plane020_1: THREE.Mesh
    Plane021: THREE.Mesh
    Plane021_1: THREE.Mesh
    Plane023: THREE.Mesh
    Plane023_1: THREE.Mesh
  }
  materials: {
    ['Material.013']: THREE.MeshStandardMaterial
    BEIGE: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    WOOD: THREE.MeshStandardMaterial
    ['WOOD PLANKS']: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    CHOCOLATE: THREE.MeshStandardMaterial
    Threshold: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/CT.glb') as GLTFResult
  if (!nodes || !materials) return null;
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder567.geometry} material={materials['Material.013']} position={[4.666, 1.919, 14.366]} rotation={[Math.PI, -0.734, Math.PI]} scale={[0.003, 0.066, 0.003]} />
      <mesh geometry={nodes.CT_BORDER.geometry} material={materials.SAND} />
      <group position={[-2.215, 0.92, 1.562]} scale={1.751}>
        <mesh geometry={nodes.Plane017.geometry} material={materials.BEIGE} />
        <mesh geometry={nodes.Plane017_1.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane017_2.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane017_3.geometry} material={materials.RED} />
      </group>
      <group position={[-2.215, -0.155, 1.562]} scale={1.751}>
        <mesh geometry={nodes.Plane024.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane024_1.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane024_2.geometry} material={materials.WHITE} />
      </group>
      <group scale={1.751}>
        <mesh geometry={nodes.Plane010.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.Plane010_2.geometry} material={materials.BLUE} />
      </group>
      <group scale={1.751}>
        <mesh geometry={nodes.Plane011.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.Plane011_2.geometry} material={materials.BLUE} />
      </group>
      <group scale={1.751}>
        <mesh geometry={nodes.Plane013.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane013_1.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.Plane013_2.geometry} material={materials.BLUE} />
      </group>
      <group scale={1.751}>
        <mesh geometry={nodes.Plane015.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane015_1.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.Plane015_2.geometry} material={materials.BLUE} />
      </group>
      <group position={[-2.215, -0.269, 1.562]} scale={1.751}>
        <mesh geometry={nodes.Plane016.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.Plane016_2.geometry} material={materials.BLUE} />
      </group>
      <group scale={1.751}>
        <mesh geometry={nodes.Plane018.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Plane018_1.geometry} material={materials.CHOCOLATE} />
        <mesh geometry={nodes.Plane018_2.geometry} material={materials.Threshold} />
      </group>
      <group scale={1.751}>
        <mesh geometry={nodes.Plane019.geometry} material={materials.CHOCOLATE} />
        <mesh geometry={nodes.Plane019_1.geometry} material={materials.Threshold} />
      </group>
      <group scale={1.751}>
        <mesh geometry={nodes.Plane020.geometry} material={materials.CHOCOLATE} />
        <mesh geometry={nodes.Plane020_1.geometry} material={materials.Threshold} />
      </group>
      <group position={[-2.215, 0.035, 1.562]} scale={1.751}>
        <mesh geometry={nodes.Plane021.geometry} material={materials.CHOCOLATE} />
        <mesh geometry={nodes.Plane021_1.geometry} material={materials.Threshold} />
      </group>
      <group position={[-2.215, 0.035, 1.562]} scale={1.751}>
        <mesh geometry={nodes.Plane023.geometry} material={materials.CHOCOLATE} />
        <mesh geometry={nodes.Plane023_1.geometry} material={materials.Threshold} />
      </group>
      <mesh geometry={nodes.Plane047.geometry} material={materials.BEIGE} />
      <mesh geometry={nodes.Plane047_1.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Plane047_2.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Plane047_3.geometry} material={materials.RED} />
      <mesh geometry={nodes.Plane047_4.geometry} material={materials.WOOD} />
      <mesh geometry={nodes.Plane047_5.geometry} material={materials['WOOD PLANKS']} />
    </group>
  )
}

useGLTF.preload('/CT.glb')
