/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/CT_AUX.glb -o components/models/CT_AUX.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CT_AUX_OBS_1: THREE.Mesh
    CT_AUX_OBS_2: THREE.Mesh
    CT_AUX_OBS_3: THREE.Mesh
    CT_AUX_OBS_4: THREE.Mesh
    CT_AUX_OBS_5: THREE.Mesh
    CT_AUX_OBS_6: THREE.Mesh
    CT_AUX_OBS_7: THREE.Mesh
    CT_AUX_OBS_8: THREE.Mesh
    CT_AUX_OBS_9: THREE.Mesh
  }
  materials: {
    ['Rope mat']: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    CHOCOLATE: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    ['WOOD PLANKS']: THREE.MeshStandardMaterial
    WOOD: THREE.MeshStandardMaterial
    ['OLD WOOD']: THREE.MeshStandardMaterial
    METAL: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/CT_AUX.glb') as GLTFResult
  if (!nodes || !materials) return null;
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CT_AUX_OBS_1.geometry} material={materials['Rope mat']} />
      <mesh geometry={nodes.CT_AUX_OBS_2.geometry} material={materials.SAND} />
      <mesh geometry={nodes.CT_AUX_OBS_3.geometry} material={materials.CHOCOLATE} />
      <mesh geometry={nodes.CT_AUX_OBS_4.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.CT_AUX_OBS_5.geometry} material={materials.SAND} />
      <mesh geometry={nodes.CT_AUX_OBS_6.geometry} material={materials['WOOD PLANKS']} />
      <mesh geometry={nodes.CT_AUX_OBS_7.geometry} material={materials.WOOD} />
      <mesh geometry={nodes.CT_AUX_OBS_8.geometry} material={materials['OLD WOOD']} />
      <mesh geometry={nodes.CT_AUX_OBS_9.geometry} material={materials.METAL} />
    </group>
  )
}

useGLTF.preload('/CT_AUX.glb')
