/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/CT_AUX.glb --output components/models/CT_AUX.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CT_AUX_OBS_1: THREE.Mesh
    CT_AUX_OBS_2: THREE.Mesh
    CT_AUX_OBS_3: THREE.Mesh
    CT_AUX_OBS_4: THREE.Mesh
    CT_AUX_OBS_5: THREE.Mesh
    CT_AUX_OBS_6: THREE.Mesh
    CT_AUX_OBS_7: THREE.Mesh
    CT_AUX_OBS_8: THREE.Mesh
    CT_AUX_OBS_9: THREE.Mesh
    CT_AUX_OBS_10: THREE.Mesh
    CT_AUX_OBS_11: THREE.Mesh
    CT_AUX_OBS_12: THREE.Mesh
  }
  materials: {
    ['Rope mat']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    Threshold: THREE.MeshStandardMaterial
    ['Dirty Wood Planks']: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    ['Old wood parquet']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/CT_AUX.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CT_AUX_OBS_1.geometry} material={materials['Rope mat']} />
      <mesh geometry={nodes.CT_AUX_OBS_2.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.CT_AUX_OBS_3.geometry} material={materials.Material} />
      <mesh geometry={nodes.CT_AUX_OBS_4.geometry} material={materials['Material.042']} />
      <mesh geometry={nodes.CT_AUX_OBS_5.geometry} material={materials['Material.017']} />
      <mesh geometry={nodes.CT_AUX_OBS_6.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.CT_AUX_OBS_7.geometry} material={nodes.CT_AUX_OBS_7.material} />
      <mesh geometry={nodes.CT_AUX_OBS_8.geometry} material={materials.Threshold} />
      <mesh geometry={nodes.CT_AUX_OBS_9.geometry} material={materials['Dirty Wood Planks']} />
      <mesh geometry={nodes.CT_AUX_OBS_10.geometry} material={materials.wood} />
      <mesh geometry={nodes.CT_AUX_OBS_11.geometry} material={materials['Old wood parquet']} />
      <mesh geometry={nodes.CT_AUX_OBS_12.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/CT_AUX.glb')
