/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/FGT.glb --output components/models/FGT.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Text001: THREE.Mesh
    Text001_1: THREE.Mesh
    Text001_2: THREE.Mesh
    Text001_3: THREE.Mesh
    Text001_4: THREE.Mesh
    Text001_5: THREE.Mesh
    Text001_6: THREE.Mesh
    Text001_7: THREE.Mesh
    Text001_8: THREE.Mesh
    Text001_9: THREE.Mesh
    Text001_10: THREE.Mesh
    Text001_11: THREE.Mesh
    Text001_12: THREE.Mesh
    Text001_13: THREE.Mesh
  }
  materials: {
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    ['Soil Ground']: THREE.MeshStandardMaterial
    Threshold: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ['Material.046']: THREE.MeshStandardMaterial
    ['Material.049']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/FGT.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, -0.028, Math.PI]}>
        <mesh geometry={nodes.Text001.geometry} material={materials['Material.031']} />
        <mesh geometry={nodes.Text001_1.geometry} material={nodes.Text001_1.material} />
        <mesh geometry={nodes.Text001_2.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Text001_3.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Text001_4.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Text001_5.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Text001_6.geometry} material={materials.Material} />
        <mesh geometry={nodes.Text001_7.geometry} material={materials['Material.066']} />
        <mesh geometry={nodes.Text001_8.geometry} material={materials['Soil Ground']} />
        <mesh geometry={nodes.Text001_9.geometry} material={materials.Threshold} />
        <mesh geometry={nodes.Text001_10.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.Text001_11.geometry} material={materials.RED} />
        <mesh geometry={nodes.Text001_12.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Text001_13.geometry} material={materials['Material.049']} />
      </group>
    </group>
  )
}

useGLTF.preload('/FGT.glb')
