/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/FGT.glb -o components/models/FGT.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    FGT2_1: THREE.Mesh
    FGT2_2: THREE.Mesh
    FGT2_3: THREE.Mesh
    FGT1_1: THREE.Mesh
    FGT1_2: THREE.Mesh
    FGT1_3: THREE.Mesh
    FGT_TEXT_1: THREE.Mesh
    FGT_TEXT_2: THREE.Mesh
    FGT_BOUNDARY: THREE.Mesh
    FGT_MARKER: THREE.Mesh
  }
  materials: {
    WHITE: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    CHOCOLATE: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/FGT.glb') as GLTFResult
  if (!nodes || !materials) return null;
  
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.356]}>
        <mesh geometry={nodes.FGT1_1.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.FGT1_2.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.FGT1_3.geometry} material={materials.RED} />
      </group>
      <mesh geometry={nodes.FGT_BOUNDARY.geometry} material={materials.SAND} />
      <mesh geometry={nodes.FGT_MARKER.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.FGT2_1.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.FGT2_2.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.FGT2_3.geometry} material={materials.RED} />
      <mesh geometry={nodes.FGT_TEXT_1.geometry} material={materials.CHOCOLATE} />
      <mesh geometry={nodes.FGT_TEXT_2.geometry} material={materials.SAND} />
    </group>
  )
}

useGLTF.preload('/FGT.glb')
