/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Gate.glb --output components/models/Gate.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder839: THREE.Mesh
    Cylinder839_1: THREE.Mesh
    Cylinder839_2: THREE.Mesh
    Cylinder839_3: THREE.Mesh
    Cylinder839_4: THREE.Mesh
    Cylinder839_5: THREE.Mesh
    Cylinder839_6: THREE.Mesh
    Cylinder839_7: THREE.Mesh
    Cylinder839_8: THREE.Mesh
  }
  materials: {
    ['Material.012']: THREE.MeshStandardMaterial
    ['The GTO']: THREE.MeshStandardMaterial
    ['Material.048']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Bricks.001']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshPhysicalMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Gate.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder839.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.Cylinder839_1.geometry} material={materials['The GTO']} />
      <mesh geometry={nodes.Cylinder839_2.geometry} material={materials['Material.048']} />
      <mesh geometry={nodes.Cylinder839_3.geometry} material={materials['Material.037']} />
      <mesh geometry={nodes.Cylinder839_4.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.Cylinder839_5.geometry} material={materials['Bricks.001']} />
      <mesh geometry={nodes.Cylinder839_6.geometry} material={materials['Material.028']} />
      <mesh geometry={nodes.Cylinder839_7.geometry} material={materials['Material.066']} />
      <mesh geometry={nodes.Cylinder839_8.geometry} material={materials['Material.044']} />
    </group>
  )
}

useGLTF.preload('/Gate.glb')
