/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Gate.glb -o components/models/Gate.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder839: THREE.Mesh
    Cylinder839_1: THREE.Mesh
    Cylinder839_2: THREE.Mesh
    Cylinder839_3: THREE.Mesh
    Cylinder839_4: THREE.Mesh
    Cylinder839_5: THREE.Mesh
    Cylinder839_6: THREE.Mesh
  }
  materials: {
    GTOPIC: THREE.MeshStandardMaterial
    SIGNAGE: THREE.MeshStandardMaterial
    LOGO: THREE.MeshStandardMaterial
    METAL: THREE.MeshStandardMaterial
    GOLD: THREE.MeshPhysicalMaterial
    WHITE_TEXT: THREE.MeshStandardMaterial
    Bricks: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Gate.glb') as GLTFResult
  if (!nodes || !materials) return null;
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder839.geometry} material={materials.GTOPIC} />
      <mesh geometry={nodes.Cylinder839_1.geometry} material={materials.SIGNAGE} />
      <mesh geometry={nodes.Cylinder839_2.geometry} material={materials.LOGO} />
      <mesh geometry={nodes.Cylinder839_3.geometry} material={materials.METAL} />
      <mesh geometry={nodes.Cylinder839_4.geometry} material={materials.GOLD} />
      <mesh geometry={nodes.Cylinder839_5.geometry} material={materials.WHITE_TEXT} />
      <mesh geometry={nodes.Cylinder839_6.geometry} material={materials.Bricks} />
    </group>
  )
}

useGLTF.preload('/Gate.glb')
