/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Ground.glb --output components/models/Ground.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane014: THREE.Mesh
    Plane014_1: THREE.Mesh
    Plane014_2: THREE.Mesh
  }
  materials: {
    ['Material.119']: THREE.MeshStandardMaterial
    ['Soil Ground']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Ground.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} />
      <mesh geometry={nodes.Plane014_1.geometry} material={materials['Material.119']} />
      <mesh geometry={nodes.Plane014_2.geometry} material={materials['Soil Ground']} />
    </group>
  )
}

useGLTF.preload('/Ground.glb')
