/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Ground.glb -o components/models/Ground.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane014: THREE.Mesh
    Plane014_1: THREE.Mesh
    Plane014_2: THREE.Mesh
  }
  materials: {
    Bricks: THREE.MeshStandardMaterial
    ['Material.119']: THREE.MeshStandardMaterial
    Grass: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Ground.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.533, 0]}>
        <mesh geometry={nodes.Plane014.geometry} material={materials.Grass || materials.Bricks} />
        <mesh geometry={nodes.Plane014_1.geometry} material={materials.Bricks} />
        <mesh geometry={nodes.Plane014_2.geometry} material={materials['Material.119']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Ground.glb')
