/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/HGT.glb -o components/models/HGT.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Text407: THREE.Mesh
    Text407_1: THREE.Mesh
    Text407_2: THREE.Mesh
    Text407_3: THREE.Mesh
  }
  materials: {
    WHITE: THREE.MeshStandardMaterial
    SAND: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/HGT.glb') as GLTFResult
  if (!nodes || !materials) return null;
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text407.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Text407_1.geometry} material={materials.SAND} />
      <mesh geometry={nodes.Text407_2.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Text407_3.geometry} material={materials.RED} />
    </group>
  )
}

useGLTF.preload('/HGT.glb')
