/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/HGT.glb --output components/models/HGT.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Text407: THREE.Mesh
    Text407_1: THREE.Mesh
    Text407_2: THREE.Mesh
    Text407_3: THREE.Mesh
    Text407_4: THREE.Mesh
    Text407_5: THREE.Mesh
    Text407_6: THREE.Mesh
    Text407_7: THREE.Mesh
    Text407_8: THREE.Mesh
    Text407_9: THREE.Mesh
  }
  materials: {
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.049']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/HGT.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text407.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Text407_1.geometry} material={materials['Material.017']} />
      <mesh geometry={nodes.Text407_2.geometry} material={materials['Material.042']} />
      <mesh geometry={nodes.Text407_3.geometry} material={materials.Material} />
      <mesh geometry={nodes.Text407_4.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Text407_5.geometry} material={nodes.Text407_5.material} />
      <mesh geometry={nodes.Text407_6.geometry} material={materials['Material.066']} />
      <mesh geometry={nodes.Text407_7.geometry} material={materials.RED} />
      <mesh geometry={nodes.Text407_8.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.Text407_9.geometry} material={materials['Material.049']} />
    </group>
  )
}

useGLTF.preload('/HGT.glb')
