/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/IND_OBS.glb -o components/models/IND_OBS.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    IND_OBS_1: THREE.Mesh
    IND_OBS_2: THREE.Mesh
    IND_OBS_3: THREE.Mesh
    IND_OBS_4: THREE.Mesh
    IND_OBS_5: THREE.Mesh
    IND_OBS_6: THREE.Mesh
    IND_OBS_7: THREE.Mesh
    IND_OBS_8: THREE.Mesh
    IND_OBS_9: THREE.Mesh
  }
  materials: {
    SAND: THREE.MeshStandardMaterial
    MEASUREMENTS: THREE.MeshStandardMaterial
    WOOD: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ROPE: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    METAL: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/IND_OBS.glb') as GLTFResult
  if (!nodes || !materials) return null;
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.IND_OBS_1.geometry} material={materials.SAND} />
      <mesh geometry={nodes.IND_OBS_2.geometry} material={materials.MEASUREMENTS} />
      <mesh geometry={nodes.IND_OBS_3.geometry} material={materials.WOOD} />
      <mesh geometry={nodes.IND_OBS_4.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.IND_OBS_5.geometry} material={materials.RED} />
      <mesh geometry={nodes.IND_OBS_6.geometry} material={materials.ROPE} />
      <mesh geometry={nodes.IND_OBS_7.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.IND_OBS_8.geometry} material={materials.SAND} />
      <mesh geometry={nodes.IND_OBS_9.geometry} material={materials.METAL} />
    </group>
  )
}

useGLTF.preload('/IND_OBS.glb')
