/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/L_OBS.glb -o components/models/L_OBS.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube112: THREE.Mesh
    Cube112_1: THREE.Mesh
    Cube112_2: THREE.Mesh
    Cube112_3: THREE.Mesh
  }
  materials: {
    MEASUREMENTS: THREE.MeshStandardMaterial
    METAL: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/L_OBS.glb') as GLTFResult
  if (!nodes || !materials) return null;
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube112.geometry} material={materials.MEASUREMENTS} />
      <mesh geometry={nodes.Cube112_1.geometry} material={materials.METAL} />
      <mesh geometry={nodes.Cube112_2.geometry} material={materials.RED} />
      <mesh geometry={nodes.Cube112_3.geometry} material={materials.WHITE} />
    </group>
  )
}

useGLTF.preload('/L_OBS.glb')
