/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/L_OBS.glb --output components/models/L_OBS.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube112: THREE.Mesh
    Cube112_1: THREE.Mesh
    Cube112_2: THREE.Mesh
    Cube112_3: THREE.Mesh
    Cube112_4: THREE.Mesh
    Cube112_5: THREE.Mesh
    Cube112_6: THREE.Mesh
    Cube112_7: THREE.Mesh
    Cube112_8: THREE.Mesh
    Cube112_9: THREE.Mesh
    Cube112_10: THREE.Mesh
    Cube112_11: THREE.Mesh
    Cube112_12: THREE.Mesh
    Cube112_13: THREE.Mesh
    Cube112_14: THREE.Mesh
  }
  materials: {
    ['Material.152']: THREE.MeshStandardMaterial
    ['House Gate']: THREE.MeshStandardMaterial
    ['Material.107']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/L_OBS.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[37.968, 0.165, -20.425]} rotation={[Math.PI, 0, Math.PI]} scale={[2.922, 0.022, 0.103]}>
        <mesh geometry={nodes.Cube112.geometry} material={nodes.Cube112.material} />
        <mesh geometry={nodes.Cube112_1.geometry} material={materials['Material.152']} />
        <mesh geometry={nodes.Cube112_2.geometry} material={materials['House Gate']} />
        <mesh geometry={nodes.Cube112_3.geometry} material={materials['Material.107']} />
        <mesh geometry={nodes.Cube112_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube112_5.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Cube112_6.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Cube112_7.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Cube112_8.geometry} material={materials.RED} />
        <mesh geometry={nodes.Cube112_9.geometry} material={materials.WHITE} />
        <mesh geometry={nodes.Cube112_10.geometry} material={materials.red} />
        <mesh geometry={nodes.Cube112_11.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube112_12.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube112_13.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube112_14.geometry} material={materials['Material.016']} />
      </group>
    </group>
  )
}

useGLTF.preload('/L_OBS.glb')
