/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/MAN.glb -t -r /public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Male_Human: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/MAN.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Male_Human.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/MAN.glb')
