/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/PGT_BASE.glb -o components/models/PGT_BASE.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ALLEYS: THREE.Mesh
    NUMBERS: THREE.Mesh
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
    Mesh_2: THREE.Mesh
    Mesh_3: THREE.Mesh
    Mesh_4: THREE.Mesh
    Mesh_5: THREE.Mesh
  }
  materials: {
    SAND: THREE.MeshStandardMaterial
    WHITE: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    BEIGE: THREE.MeshStandardMaterial
    WOOD: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    BLACK: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/PGT_BASE.glb') as GLTFResult
  if (!nodes || !materials) return null;
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ALLEYS.geometry} material={materials.SAND} />
      <mesh geometry={nodes.NUMBERS.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Mesh.geometry} material={materials.WHITE} />
      <mesh geometry={nodes.Mesh_1.geometry} material={materials.BLUE} />
      <mesh geometry={nodes.Mesh_2.geometry} material={materials.BEIGE} />
      <mesh geometry={nodes.Mesh_3.geometry} material={materials.WOOD} />
      <mesh geometry={nodes.Mesh_4.geometry} material={materials.RED} />
      <mesh geometry={nodes.Mesh_5.geometry} material={materials.BLACK} />
    </group>
  )
}

useGLTF.preload('/PGT_BASE.glb')
