/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/PGT_BASE.glb --output components/models/PGT_BASE.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube1286: THREE.Mesh
    Cube1286_1: THREE.Mesh
    Cube1286_2: THREE.Mesh
    Cube1286_3: THREE.Mesh
    Cube1286_4: THREE.Mesh
    Cube1286_5: THREE.Mesh
    Cube1286_6: THREE.Mesh
    Cube1286_7: THREE.Mesh
    Cube1286_8: THREE.Mesh
    Cube1286_9: THREE.Mesh
    Cube1286_10: THREE.Mesh
    Cube1286_11: THREE.Mesh
    Cube1286_12: THREE.Mesh
    Cube1286_13: THREE.Mesh
    Cube1286_14: THREE.Mesh
    Cube1286_15: THREE.Mesh
    Cube1286_16: THREE.Mesh
    Cube1286_17: THREE.Mesh
    Cube1286_18: THREE.Mesh
    Cube1286_19: THREE.Mesh
    Cube1286_20: THREE.Mesh
    Cube1286_21: THREE.Mesh
    Cube1286_22: THREE.Mesh
    Cube1286_23: THREE.Mesh
    Cube1286_24: THREE.Mesh
    Cube1286_25: THREE.Mesh
  }
  materials: {
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.070']: THREE.MeshStandardMaterial
    ['Material.056']: THREE.MeshStandardMaterial
    RED: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    BLUE: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.131']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.046']: THREE.MeshStandardMaterial
    ['Material.049']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.170']: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/PGT_BASE.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube1286.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Cube1286_1.geometry} material={nodes.Cube1286_1.material} />
        <mesh geometry={nodes.Cube1286_2.geometry} material={materials['Material.070']} />
        <mesh geometry={nodes.Cube1286_3.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Cube1286_4.geometry} material={materials.RED} />
        <mesh geometry={nodes.Cube1286_5.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube1286_6.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cube1286_7.geometry} material={materials.BLUE} />
        <mesh geometry={nodes.Cube1286_8.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Cube1286_9.geometry} material={materials['Material.131']} />
        <mesh geometry={nodes.Cube1286_10.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Cube1286_11.geometry} material={materials['Material.026']} />
        <mesh geometry={nodes.Cube1286_12.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube1286_13.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Cube1286_14.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Cube1286_15.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube1286_16.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Cube1286_17.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube1286_18.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Cube1286_19.geometry} material={materials['Material.049']} />
        <mesh geometry={nodes.Cube1286_20.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Cube1286_21.geometry} material={materials['Material.066']} />
        <mesh geometry={nodes.Cube1286_22.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube1286_23.geometry} material={materials['Material.170']} />
        <mesh geometry={nodes.Cube1286_24.geometry} material={materials.wood} />
        <mesh geometry={nodes.Cube1286_25.geometry} material={materials['Material.023']} />
      </group>
    </group>
  )
}

useGLTF.preload('/PGT_BASE.glb')
