/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Trees.glb -o components/models/Trees.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube024: THREE.Mesh
    Cube024_1: THREE.Mesh
    Cube023: THREE.Mesh
    Cube023_1: THREE.Mesh
    Cube022: THREE.Mesh
    Cube022_1: THREE.Mesh
    Cube017: THREE.Mesh
    Cube017_1: THREE.Mesh
  }
  materials: {
    ['LP_bark.003']: THREE.MeshStandardMaterial
    ['LP_wood.003']: THREE.MeshStandardMaterial
    ['LP_bark.002']: THREE.MeshStandardMaterial
    ['LP_wood.002']: THREE.MeshStandardMaterial
    ['LP_bark.001']: THREE.MeshStandardMaterial
    ['LP_wood.001']: THREE.MeshStandardMaterial
    LP_bark: THREE.MeshStandardMaterial
    LP_wood: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Trees.glb') as GLTFResult
  if (!nodes || !materials) return null;
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube024.geometry} material={materials['LP_bark.003']} />
      <mesh geometry={nodes.Cube024_1.geometry} material={materials['LP_wood.003']} />
      <mesh geometry={nodes.Cube023.geometry} material={materials['LP_bark.002']} />
      <mesh geometry={nodes.Cube023_1.geometry} material={materials['LP_wood.002']} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['LP_bark.001']} />
      <mesh geometry={nodes.Cube022_1.geometry} material={materials['LP_wood.001']} />
      <mesh geometry={nodes.Cube017.geometry} material={materials.LP_bark} />
      <mesh geometry={nodes.Cube017_1.geometry} material={materials.LP_wood} />
    </group>
  )
}

useGLTF.preload('/Trees.glb')
